- name: Add Mo user
  user:
    name: mo
    uid: 1000
    comment: mo
    group: mo
    groups: docker,wheel,vboxsf,vboxusers,pkg-build
    create_home: no
    home: /home/mo
    state: present

- name: Add Guest to group
  group:
    name: guest
    gid: 1002
    state: present

- name: Add Guest user
  user:
    name: guest
    uid: 1001
    comment: guest
    group: guest
    create_home: yes
    home: /home/guest
    state: present

- name: Add Mo to sudoers
  copy:
    src: "{{ role_path }}/env/mo.conf"
    dest: /etc/sudoers.d/mo.conf
    owner: root
    group: root
    mode: "0644"